### ISSUE TITLE
Takes too long to get kr00k packet

### ISSUE THREAD

**Issue by sudo-su-FDEL** [hexway/r00kie-kr00kie#1]
Basically it keeps sending deauth packets, and havennt been successful in getting the kr00ked packet

**Comment by hexway** [comment]
For testing purpose you can generate traffic on the victim side using  [traffic_generator.py](https://github.com/hexway/r00kie-kr00kie/blob/master/traffic_generator.py) from this repo

**Comment by sudo-su-FDEL** [comment]
okay, should that be done before or during deauth?

**Comment by hexway** [comment]
before deauth
